### ISSUE TITLE
General Code Health

### ISSUE THREAD

**Issue by efir-tractatus** [Faworki/project-catwalk#53]
[ReviewsWidget.jsx](client/components/ReviewsWidget.jsx) is very large. While it is well organized, could it be split apart into a more readable structure?
For instance, I notice that you are mixing a class component with functional sub-components that are using the state hook. Consider whether you need to keep all those helper functions in the class component. 
Can you use the state hook to migrate some of those helper functions into their respective sub-components?

**Comment by trentgoing** [comment]
Agreed with Denis here!   One way to look at this might be "does this code directly access state, or update the view?".  If there is logic that doesn't necessarily change state or render, it probably could be isolated into a helper function.    This 1. keeps the component clean, and limited to just the code needed for React, 2. makes the helper logic discrete and more easily tested (think about how much clearer inputs > outputs would be without React included)

**Comment by trentgoing** [comment]
https://github.com/Faworki/project-catwalk/blob/ad8b284b6908b50add73bfd7529361e4f0801917/client/components/App.jsx#L74-L88
Here's another example of a helper function that isn't connecting to React, and could be defined in its own isolated, testable way
